![imagen](./img/ejercicios.png)

In [1]:
import numpy as np

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [3]:
my_array = np.arange(10)
print(my_array[::-2])

[9 7 5 3 1]


In [5]:
my_array[my_array % 2 == 1][::-1]

array([9, 7, 5, 3, 1])

## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [6]:
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
print(my_array[-2:-4:-1])

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [9]:
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


In [10]:
print(my_array[2::-1])

[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [14]:
ejer_4 = np.arange(1,21).reshape(4,5)
ejer_4

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [15]:
print(ejer_4[::-1, ::-1])

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


In [16]:
ejer_4.T

array([[ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19],
       [ 5, 10, 15, 20]])

In [17]:
print(np.flip(ejer_4))

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [18]:
print(ejer_4)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [19]:
print(ejer_4[:2,:2])

[[1 2]
 [6 7]]


In [23]:
np.flip(ejer_4)

array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

In [30]:
np.flip(ejer_4)[-1:-3:-1, -1:-3:-1]

array([[1, 2],
       [6, 7]])

## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [32]:
print(ejer_4[::2, ::2])

[[ 1  3  5]
 [11 13 15]]


## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [35]:
print(ejer_4)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [34]:
ejer_4[:3, ::-1]

array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])

## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [36]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

In [37]:
x == "Loro"

array([ True, False, False,  True, False])

In [38]:
x[x == "Loro"]

array(['Loro', 'Loro'], dtype='<U5')

In [39]:
np.where(x == "Loro", True, False)

array([ True, False, False,  True, False])

In [40]:
x[np.where(x == "Loro", True, False)]

array(['Loro', 'Loro'], dtype='<U5')

In [41]:
np.extract(x == "Loro", x)

array(['Loro', 'Loro'], dtype='<U5')

## Ejercicio 9
Crea una secuencia de 20 elementos y transfórmala en un array compuesto por 2 matrices de 5x2

In [42]:
x = np.arange(20).reshape(2,5,2)
print(x)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]


In [44]:
print(x.ndim)
print(x.shape)
print(x.size)

3
(2, 5, 2)
20


## Ejercicio 10

Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [45]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [46]:
print(x.itemsize)
print(x.nbytes)
print(x.dtype)

8
80
float64


In [62]:
x = np.full(10, 0)
print(x)
print(x.itemsize)
print(x.nbytes)
print(x.dtype)

[0 0 0 0 0 0 0 0 0 0]
4
40
int32


In [64]:
x = np.full(10, 0, dtype=np.int8)
print(x)
print(x.itemsize)
print(x.nbytes)
print(x.dtype)

[0 0 0 0 0 0 0 0 0 0]
1
10
int8


In [49]:
2 **8

256

In [ ]:
# [0, 255]
# [-128,127]

In [65]:
x[0] = 128
print(x)

[-128    0    0    0    0    0    0    0    0    0]


In [66]:
x[3] = 1
print(x)

[-128    0    0    1    0    0    0    0    0    0]


## Ejercicio 11

Crea un vector que vaya del 10 al 49

Inviértelo

In [68]:
x = np.arange(10,50)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [69]:
np.flip(x)

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [70]:
print(x[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejercicio 12
Encuentra los índices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/) Encapsúlalo en una función, con un argumento de entrada de un vector.

In [71]:
ejer_12 = np.array([1,2,0,0,4,0])

In [75]:
np.where(ejer_12 != 0)[0]

array([0, 1, 4], dtype=int64)

In [76]:
def ejer_12(vector):
    return np.where(vector != 0)[0]

In [77]:
v1 = np.array([5,2,0,3,0,0,1])
ejer_12(v1)

array([0, 1, 3, 6], dtype=int64)

In [99]:
np.nonzero(v1)[0]

array([0, 1, 3, 6], dtype=int64)

## Ejercicio 13
Crea una matriz de números aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [152]:
x = np.random.randint(100, size=(10,10))
print(x)
print(x.min())
print(x.max())
print(x.mean())
print(np.median(x))
# print(np.mode(x))
print(x.std())

[[60 93 68 94 90 56 47 39 25  7]
 [45 86 43 34 13 75 70 45 45 46]
 [88 37 20 91 58 59 64 38 34 82]
 [71  4 14 62 41 87  1 22 89 27]
 [65 28 83 52 37 15 82 75 18 99]
 [56  3 69 33 42 80 25 19 52 29]
 [82 99  7 72 14 35 83 85 83  8]
 [71 36 41 63 64 51 71 45 78  3]
 [ 8 96 14 50  5 88 57 25 32 33]
 [94 45 19 54 11  4 48 73  4 39]]
1
99
49.22
46.5
28.203042389075687


## Ejercicio 14
Crea un vector aleatorio de tamaño 30 y calcula su media

In [201]:
np.random.seed(536)
x = np.random.random(30)
print(x)
print(x.mean())
print(x.sum()/len(x))

[0.00795949 0.58140435 0.38437322 0.22877009 0.96101977 0.17622722
 0.44836979 0.32949757 0.41750623 0.20343024 0.90919714 0.50623051
 0.99886485 0.29256153 0.19065593 0.00799178 0.53629833 0.95124447
 0.33373733 0.70946032 0.32087297 0.03844602 0.3842427  0.70729365
 0.1257555  0.59192648 0.72293155 0.07746711 0.15242086 0.35942609]
0.4218527686976443
0.4218527686976443


## Ejercicio 15
Crea un array cuadrado de 2D, con las dimensiones que quieras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [203]:
ejer_15 = np.full((10,10), 1)
ejer_15

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [204]:
ejer_15[1:-1, 1:-1] = 0
print(ejer_15)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [210]:
ejer_15 = np.full((10,10), 0)
ejer_15

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [214]:
# ejer_15[0, :] = 1
ejer_15[::9,::] = 1
ejer_15[::,::9] = 1
print(ejer_15)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [215]:
def f_ejer_15(tamaño):
    matrix = np.full(tamaño, 1)
    matrix[1:-1, 1:-1] = 0
    return matrix

In [218]:
f_ejer_15((3,3))

array([[1, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

In [219]:
f_ejer_15((13,13))

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [220]:
f_ejer_15((5,5))

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

## Ejercicio 16
Crea una matriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [221]:
x = np.full((8,8), 0)
print(x)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [223]:
x[::2, 1::2] = 1
x[1::2, ::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 17
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [224]:
a = np.array([[1,0],
              [0,1]])
print(a)

[[1 0]
 [0 1]]


In [229]:
x = np.tile(a, (4,4))
print(x)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


## Ejercicio 18
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [234]:
x = np.random.randint(1,20, (5,5))
print(x)

[[ 2 14  4  1  9]
 [10  5 13  2  5]
 [ 5  3 12 17  2]
 [10 12  4  1 16]
 [11  6 18 13 11]]


In [235]:
np.mean(x)

8.24

In [236]:
np.std(x)

5.225169853698538

In [237]:
x_norm = (x - np.mean(x)) / np.std(x)
print(x_norm)

[[-1.19421955  1.10235651 -0.81145687 -1.38560089  0.14544982]
 [ 0.33683116 -0.62007554  0.91097517 -1.19421955 -0.62007554]
 [-0.62007554 -1.00283821  0.71959383  1.67650052 -1.19421955]
 [ 0.33683116  0.71959383 -0.81145687 -1.38560089  1.48511919]
 [ 0.52821249 -0.4286942   1.86788186  0.91097517  0.52821249]]


In [243]:
np.round(x_norm.mean(),0)

-0.0

In [244]:
x_norm.std()

1.0

## Ejercicio 19
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [253]:
x = np.arange(11)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [ ]:
# and &
# or |
# not ~

In [ ]:
y = x.copy()
y[(y >=3) & (y <= 8)] = -1
print(y)

[ 0  1  2 -1 -1 -1 -1 -1 -1  9 10]


In [255]:
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [262]:
z = x.copy()
z[(z >=3) & (z <= 8)] *= (-1)
print(z)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]


In [263]:
z = x.copy()
np.where((z >=3) & (z <= 8), z*(-1), z)

array([ 0,  1,  2, -3, -4, -5, -6, -7, -8,  9, 10])

preguntas...

In [268]:
np.arange(125).reshape(5,5,5)[1][1][2]

32